const BestSellsData = [
  {
    id: "1",
    name: "OV32150",
    image: "onvo.webp",
    imageFile: "TelevisionImage",
    description: "81 Screen HD Ready Smart LED TV with Satellite Receiver",
    brand: "Onvo",
    category: "television",
    price: 499,
    chechFavorites: false,
    favoriteId: 25,
  },
  {
    id: "2",
    name: "50R754U",
    image: "regal.webp",
    imageFile: "TelevisionImage",
    description: "126 Screen 4K Ultra HD Smart LED TV with Satellite Receiver",
    brand: "Regal",
    category: "television",
    price: 699,
    chechFavorites: false,
    favoriteId: 26,
  },
  {
    id: "3",
    name: "T500",
    image: "jbl.webp",
    imageFile: "HeadPhoneImage",
    description: "Black Wired On-Ear Headphones",
    brand: "JBL",
    category: "headphone",
    price: 149,
    chechFavorites: false,
    favoriteId: 19,
  },

  {
    id: "4",
    name: "Stellia High-end",
    image: "focal.webp",
    imageFile: "HeadPhoneImage",
    description: "Brown On-Ear Wired Headphones",
    brand: "Focal",
    category: "headphone",
    price: 1999,
    chechFavorites: false,
    favoriteId: 20,
  },
  {
    id: "3",
    name: "B242e1gsj",
    image: "philips.webp",
    imageFile: "MonitorImage",
    description: " 144hz 1ms Hdmi+dp Freesync Fullhd Va Gaming Monitor",
    brand: "Philips",
    category: "monitor",
    price: 369,
    chechFavorites: false,
    favoriteId: 35,
  },
  {
    id: "4",
    name: "Gb-2461cf",
    image: "gamebooster.webp",
    imageFile: "MonitorImage",
    description: " 144hz 1ms Curved Freesync Fhd 2xhdmi 1xdp Gaming Monitor",
    brand: "Gamebooster",
    category: "monitor",
    price: 339,
    chechFavorites: false,
    favoriteId: 36,
  },
  {
    id: "1",
    name: "MacBook Air",
    image: "macbook.webp",
    imageFile: "LaptopImage",
    description: " 8-Core CPU 7-Core GPU 8GB Unified Memory 256GB SSD",
    brand: "Apple",
    category: "laptop",
    price: 999,
    chechFavorites: false,
    favoriteId: 1,
  },
  {
    id: "2",
    name: "Casper Excalibur",
    image: "casper.webp",
    imageFile: "LaptopImage",
    description:
      "Excalibur G911.1270-bv60x-b Intel I7-12700h 16gb Ram 500gb Ssd 6gb Rtx3060",
    brand: "Casper",
    category: "laptop",
    price: 1199,
    chechFavorites: false,
    favoriteId: 2,
  },
];

export default BestSellsData;
