const HeadPhoneData = [
  {
    id: 1,
    name: "Sony Wh-ch510",
    image: "sony.webp",
    imageFile: "HeadPhoneImage",
    description: " Black Wireless Bluetooh On-Ear Headphones",
    brand: "Sony",
    category: "headphone",
    price: 199,
    countInStock: 86,
    rating: 4,
    numReviews: 238,
    connection: "Bluetooth",
    usageType: "On-ear",
    activeNoiseCancellation: "There Is",
    headphoneModel: "On-Ear Full Length",
    color: "Black",
    microphone: "There Is",
    chechFavorites: false,
    productUnicId: 17,
  },
  {
    id: 2,
    name: "Philips Tah4105",
    image: "philips.webp",
    imageFile: "HeadPhoneImage",
    description: "Black Wired On-Ear Headphones",
    brand: "Philips",
    category: "headphone",
    price: 99,
    countInStock: 96,
    rating: 4,
    numReviews: 338,
    connection: "Wired",
    usageType: "On-ear",
    activeNoiseCancellation: "None",
    headphoneModel: "On-Ear Full Length",
    color: "Black",
    microphone: "There Is",
    chechFavorites: false,
    productUnicId: 18,
  },
  {
    id: 3,
    name: "JBL T500",
    image: "jbl.webp",
    imageFile: "HeadPhoneImage",
    description: "Black Wired On-Ear Headphones",
    brand: "JBL",
    category: "headphone",
    price: 149,
    countInStock: 108,
    rating: 3,
    numReviews: 356,
    connection: "Wired",
    usageType: "On-ear",
    activeNoiseCancellation: "None",
    headphoneModel: "On-Ear Full Length",
    color: "Black",
    microphone: "There Is",
    chechFavorites: false,
    productUnicId: 19,
  },

  {
    id: 4,
    name: "Focal Stellia High-end",
    image: "focal.webp",
    imageFile: "HeadPhoneImage",
    description: "Brown On-Ear Wired Headphones",
    brand: "Focal",
    category: "headphone",
    price: 1999,
    countInStock: 8,
    rating: 3,
    numReviews: 956,
    connection: "Wired",
    usageType: "On-ear",
    activeNoiseCancellation: "None",
    headphoneModel: "On-Ear Full Length",
    color: "Black",
    microphone: "There Is",
    chechFavorites: false,
    productUnicId: 20,
  },

  {
    id: 5,
    name: "Sennheiser Hd 800 S",
    image: "sennheiser.jpg",
    imageFile: "HeadPhoneImage",
    description: "Black On-Ear Wired Headphones",
    brand: "Sennheiser",
    category: "headphone",
    price: 1599,
    countInStock: 15,
    rating: 3,
    numReviews: 756,
    connection: "Wired",
    usageType: "On-ear",
    activeNoiseCancellation: "There Is",
    headphoneModel: "On-Ear Full Length",
    color: "Black",
    microphone: "There Is",
    chechFavorites: false,
    productUnicId: 21,
  },

  {
    id: 6,
    name: "Beyerdynamic T1 32 Ohm",
    image: "beyerDynamic.jpg",
    imageFile: "HeadPhoneImage",
    description: "3rd Generation On-Ear Headphones",
    brand: "Beyerdynamic",
    category: "headphone",
    price: 1399,
    countInStock: 23,
    rating: 3,
    numReviews: 496,
    connection: "Wired",
    usageType: "On-ear",
    activeNoiseCancellation: "There Is",
    headphoneModel: "On-Ear Full Length",
    color: "Black",
    microphone: "There Is",
    chechFavorites: false,
    productUnicId: 22,
  },

  {
    id: 7,
    name: "Beyerdynamic Airpods Max",
    image: "apple.webp",
    imageFile: "HeadPhoneImage",
    description: "Green Wireless On-Ear Headphones",
    brand: "Beyerdynamic",
    category: "headphone",
    price: 1199,
    countInStock: 31,
    rating: 5,
    numReviews: 446,
    connection: "Bluetooth",
    usageType: "On-ear",
    activeNoiseCancellation: "There Is",
    headphoneModel: "On-Ear Full Length",
    color: "Green",
    microphone: "There Is",
    chechFavorites: false,
    productUnicId: 23,
  },

  {
    id: 8,
    name: "ASUS Rog Delta S",
    image: "asus.jpg",
    imageFile: "HeadPhoneImage",
    description: "RGB 7.1 Gaming Headphones",
    brand: "ASUS",
    category: "headphone",
    price: 1099,
    countInStock: 37,
    rating: 4,
    numReviews: 516,
    connection: "Wired",
    usageType: "On-ear",
    activeNoiseCancellation: "There Is",
    headphoneModel: "On-Ear Full Length",
    color: "Black",
    microphone: "There Is",
    chechFavorites: false,
    productUnicId: 24,
  },
];

export default HeadPhoneData;
