const HeadPhoneData = [
    {
        id: "1",
        name: "Wh-ch510",
        image: "sony.webp",
        description: " Black Wireless Bluetooh On-Ear Headphones",
        brand: "Sony",
        category: "Electronics",
        price: 199,
        countInStock: 86,
        rating: 4,
        numReviews: 238,
        connection: "Bluetooth",
        usageType: "On-ear",
        activeNoiseCancellation: "There Is",
        headphoneModel: "On-Ear Full Length",
        color: "Black",
        microphone: "There Is"
    },
    {
        id: "2",
        name: "Tah4105",
        image: "philips.webp",
        description: "Black Wired On-Ear Headphones",
        brand: "Philips",
        category: "Electronics",
        price: 99,
        countInStock: 96,
        rating: 4,
        numReviews: 338,
        connection: "Wired",
        usageType: "On-ear",
        activeNoiseCancellation: "None",
        headphoneModel: "On-Ear Full Length",
        color: "Black",
        microphone: "There Is"
    },
    {
        id: "3",
        name: "T500",
        image: "jbl.webp",
        description: "Black Wired On-Ear Headphones",
        brand: "JBL",
        category: "Electronics",
        price: 149,
        countInStock: 108,
        rating: 3,
        numReviews: 356,
        connection: "Wired",
        usageType: "On-ear",
        activeNoiseCancellation: "None",
        headphoneModel: "On-Ear Full Length",
        color: "Black",
        microphone: "There Is"
    },

    {
        id: "4",
        name: "Stellia High-end",
        image: "focal.webp",
        description: "Brown On-Ear Wired Headphones",
        brand: "Focal",
        category: "Electronics",
        price: 1999,
        countInStock: 8,
        rating: 3,
        numReviews: 956,
        connection: "Wired",
        usageType: "On-ear",
        activeNoiseCancellation: "None",
        headphoneModel: "On-Ear Full Length",
        color: "Black",
        microphone: "There Is"
    },


    {
        id: "5",
        name: "Hd 800 S",
        image: "sennheiser.jpg",
        description: "Black On-Ear Wired Headphones",
        brand: "Sennheiser",
        category: "Electronics",
        price: 1599,
        countInStock: 15,
        rating: 3,
        numReviews: 756,
        connection: "Wired",
        usageType: "On-ear",
        activeNoiseCancellation: "There Is",
        headphoneModel: "On-Ear Full Length",
        color: "Black",
        microphone: "There Is"
    },

    {
        id: "6",
        name: "T1 32 Ohm",
        image: "beyerDynamic.jpg",
        description: "3rd Generation On-Ear Headphones",
        brand: "Beyerdynamic",
        category: "Electronics",
        price: 1399,
        countInStock: 23,
        rating: 3,
        numReviews: 496,
        connection: "Wired",
        usageType: "On-ear",
        activeNoiseCancellation: "There Is",
        headphoneModel: "On-Ear Full Length",
        color: "Black",
        microphone: "There Is"
    },

    {
        id: "7",
        name: "Airpods Max",
        image: "apple.webp",
        description: "Green Wireless On-Ear Headphones",
        brand: "Beyerdynamic",
        category: "Electronics",
        price: 1199,
        countInStock: 31,
        rating: 5,
        numReviews: 446,
        connection: "Bluetooth",
        usageType: "On-ear",
        activeNoiseCancellation: "There Is",
        headphoneModel: "On-Ear Full Length",
        color: "Green",
        microphone: "There Is"
    },

    {
        id: "8",
        name: "Rog Delta S",
        image: "asus.jpg",
        description: "RGB 7.1 Gaming Headphones",
        brand: "ASUS",
        category: "Electronics",
        price: 1099,
        countInStock: 37,
        rating: 4,
        numReviews: 516,
        connection: "Wired",
        usageType: "On-ear",
        activeNoiseCancellation: "There Is",
        headphoneModel: "On-Ear Full Length",
        color: "Black",
        microphone: "There Is"
    },

];

export default HeadPhoneData;