const HighlightsData = [
  {
    id: "1",
    name: "iPhone 11",
    image: "iphone.webp",
    imageFile: "PhoneImage",
    description: "128GB Box White Cell Phone Without Accessories",
    brand: "Apple",
    category: "phone",
    price: 1099,
    chechFavorites: false,
    favoriteId: 9,
  },

  {
    id: "3",
    name: "50U9600",
    image: "vestel.webp",
    imageFile: "TelevisionImage",
    description:
      "127 Screen Satellite Receiver 4K Ultra HD Smart LED TV TV-U9600",
    brand: "Vestel",
    category: "television",
    price: 799,
    chechFavorites: false,
    favoriteId: 27,
  },

  {
    id: "7",
    name: "Airpods Max",
    image: "apple.webp",
    imageFile: "HeadPhoneImage",
    description: "Green Wireless On-Ear Headphones",
    brand: "Beyerdynamic",
    category: "headphone",
    price: 1199,
    chechFavorites: false,
    favoriteId: 23,
  },

  {
    id: "2",
    name: "Redmi 10",
    image: "xiaomi.webp",
    imageFile: "PhoneImage",
    description: "2022 4GB Ram + 64GB Gray Mobile Phone",
    brand: "Xiaomi",
    category: "phone",
    price: 599,
    chechFavorites: false,
    favoriteId: 10,
  },

  {
    id: "5",
    name: "Monster Abra",
    image: "monster.webp",
    imageFile: "LaptopImage",
    description: "Intel Core I5-12500h 8 Gb Ram 500gb Ssd 4gb Gtx1650",
    brand: "Monster",
    category: "laptop",
    price: 799,
    chechFavorites: false,
    favoriteId: 5,
  },

  {
    id: "4",
    name: "SN55UAL402",
    image: "sunny.webp",
    imageFile: "TelevisionImage",
    description: "139 Screen 4K Ultra HD Smart LED TV with Satellite Receiver",
    brand: "Sunny",
    category: "television",
    price: 699,
    chechFavorites: false,
    favoriteId: 28,
  },

  {
    id: "8",
    name: "Rog Delta S",
    image: "asus.jpg",
    imageFile: "HeadPhoneImage",
    description: "RGB 7.1 Gaming Headphones",
    brand: "ASUS",
    category: "headphone",
    price: 1099,
    chechFavorites: false,
    favoriteId: 24,
  },

  {
    id: "6",
    name: "Msi Alpha",
    image: "msi.webp",
    imageFile: "LaptopImage",
    description: "R7-5800H 16GB DDR4 RX6600M GDDR6 8GB 512GB SSD",
    brand: "Msi",
    category: "laptop",
    chechFavorites: false,
    price: 899,
  },
];

export default HighlightsData;
