const LaptopData = [
  {
    id: 1,
    name: "MacBook Air",
    image: "macbook.webp",
    imageFile: "LaptopImage",
    description: " 8-Core CPU 7-Core GPU 8GB Unified Memory 256GB SSD",
    brand: "Apple",
    category: "laptop",
    price: 999,
    countInStock: 10,
    rating: 4,
    numReviews: 12,
    processorType: "Apple M1",
    processorSystem: "Mac Os",
    ram: "8 GB",
    ssdCapacity: "256 GB",
    displayCard: "Internal Card",
    warrantyType: "Official Distributor",
    chechFavorites: false,
    productUnicId: 1,
  },
  {
    id: 2,
    name: "Casper Excalibur",
    image: "casper.webp",
    imageFile: "LaptopImage",
    description:
      "Excalibur G911.1270-bv60x-b Intel I7-12700h 16gb Ram 500gb Ssd 6gb Rtx3060",
    brand: "Casper",
    category: "laptop",
    price: 1199,
    countInStock: 15,
    rating: 3,
    numReviews: 17,
    processorType: "Intel Core i7",
    processorSystem: "Free Dos",
    ram: "16 GB",
    ssdCapacity: "500 GB",
    displayCard: "Nvidia GeForce RTX3060",
    warrantyType: "Official Distributor",
    chechFavorites: false,
    productUnicId: 2,
  },
  {
    id: 3,
    name: "Hp Victus",
    image: "hp.webp",
    imageFile: "LaptopImage",
    description: "Ryzen 7 6800h 16gb Ram 512gb Ssd 4gb Rtx3050ti",
    brand: "Hp",
    category: "laptop",
    price: 899,
    countInStock: 23,
    rating: 4,
    numReviews: 19,
    processorType: "Ryzen 7 6800h",
    processorSystem: "Free Dos",
    ram: "16 GB",
    ssdCapacity: "512 GB",
    displayCard: "Nvidia GeForce RTX 3050 Ti",
    warrantyType: "Official Distributor",
    chechFavorites: false,
    productUnicId: 3,
  },
  {
    id: 4,
    name: "Asus Rog Strıx",
    image: "asus.jpg",
    imageFile: "LaptopImage",
    description: "I9-12950hx 32gb 4tb Ssd 16gb Rtx3080tı",
    brand: "Asus",
    category: "laptop",
    price: 5999,
    countInStock: 3,
    rating: 5,
    processorType: "Intel Core i9",
    processorSystem: "Free Dos",
    ram: "32 GB",
    ssdCapacity: "4 TB",
    displayCard: "Nvidia GeForce RTX 3080 Ti",
    warrantyType: "Official Distributor",
    chechFavorites: false,
    productUnicId: 4,
  },
  {
    id: 5,
    name: "Monster Abra",
    image: "monster.webp",
    imageFile: "LaptopImage",
    description: "Intel Core I5-12500h 8 Gb Ram 500gb Ssd 4gb Gtx1650",
    brand: "Monster",
    category: "laptop",
    price: 799,
    countInStock: 26,
    rating: 2,
    processorType: "Intel Core I5-12500h",
    processorSystem: "Free Dos",
    ram: "16 GB",
    ssdCapacity: "500 GB",
    displayCard: "Nvidia GeForce GTX 1650",
    warrantyType: "Official Distributor",
    chechFavorites: false,
    productUnicId: 5,
  },
  {
    id: 6,
    name: "Msi Alpha",
    image: "msi.webp",
    imageFile: "LaptopImage",
    description: "R7-5800H 16GB DDR4 RX6600M GDDR6 8GB 512GB SSD",
    brand: "Msi",
    category: "laptop",
    price: 899,
    countInStock: 52,
    rating: 4,
    numReviews: 21,
    processorType: "AMD Ryzen 7",
    processorSystem: "Free Dos",
    ram: "8 GB",
    ssdCapacity: "512 GB",
    displayCard: "Internal Card",
    warrantyType: "Official Distributor",
    chechFavorites: false,
    productUnicId: 6,
  },
  {
    id: 7,
    name: "Hp Pavilion",
    image: "hp2.webp",
    imageFile: "LaptopImage",
    description: "Intel Core I5 10300h Gtx1050",
    brand: "Hp",
    category: "laptop",
    price: 699,
    countInStock: 38,
    rating: 1,
    numReviews: 29,
    processorType: "Intel Core i5",
    processorSystem: "Free Dos",
    ram: "8 GB",
    ssdCapacity: "512 GB",
    displayCard: "Nvidia GeForce GTX1650 Ti",
    warrantyType: "Official Distributor",
    chechFavorites: false,
    productUnicId: 7,
  },
  {
    id: 8,
    name: "Msi Thın",
    image: "msi2.webp",
    imageFile: "LaptopImage",
    description: "I5-10500h 8gb Ram 256gb Ssd Gtx1650",
    brand: "Msi",
    category: "laptop",
    price: 899.0,
    countInStock: 43,
    rating: 2,
    numReviews: 46,
    processorType: "Intel Core i5",
    processorSystem: "Free Dos",
    ram: "8 GB",
    ssdCapacity: "256 GB",
    displayCard: "Nvidia GeForce GTX1650",
    warrantyType: "Official Distributor",
    chechFavorites: false,
    productUnicId: 8,
  },
];

export default LaptopData;
