const MonitorData = [
  {
    id: 1,
    name: "Odyssey G3",
    image: "samsung.webp",
    imageFile: "MonitorImage",
    description: " 165hz 1ms Hdmi Dp Freesync VA Black Gaming Monitor",
    brand: "Samsung",
    category: "monitor",
    price: 499,
    countInStock: 48,
    rating: 4,
    numReviews: 278,
    screenSize: 27,
    resolution: "1920 x 1080",
    reactionTime: "1ms",
    warrantyType: "Official Distributor",
    panelType: "VA",
    Imagingtechnology: "LED",
    chechFavorites: false,
    favoriteId: 33,
  },
  {
    id: 2,
    name: "Black Eagle",
    image: "rampage.webp",
    imageFile: "MonitorImage",
    description:
      " 27 Fhd 165hz Ips Panel Vga + Hdmi * 2 + Dp Flat Pc Player Monitor",
    brand: "Rampage",
    category: "monitor",
    price: 399,
    countInStock: 59,
    rating: 4,
    numReviews: 228,
    screenSize: 27,
    resolution: "1920 x 1080",
    reactionTime: "1ms",
    warrantyType: "Official Distributor",
    panelType: "IPS",
    Imagingtechnology: "IPS",
    chechFavorites: false,
    favoriteId: 34,
  },
  {
    id: 3,
    name: "B242e1gsj",
    image: "philips.webp",
    imageFile: "MonitorImage",
    description: " 144hz 1ms Hdmi+dp Freesync Fullhd Va Gaming Monitor",
    brand: "Philips",
    category: "monitor",
    price: 369,
    countInStock: 85,
    rating: 4,
    numReviews: 218,
    screenSize: 23.8,
    resolution: "1920 x 1080",
    reactionTime: "1ms",
    warrantyType: "Official Distributor",
    panelType: "VA",
    Imagingtechnology: "VA",
    chechFavorites: false,
    favoriteId: 35,
  },
  {
    id: 4,
    name: "Gb-2461cf",
    image: "gamebooster.webp",
    imageFile: "MonitorImage",
    description: " 144hz 1ms Curved Freesync Fhd 2xhdmi 1xdp Gaming Monitor",
    brand: "Gamebooster",
    category: "monitor",
    price: 339,
    countInStock: 106,
    rating: 4,
    numReviews: 315,
    screenSize: 24,
    resolution: "1920 x 1080",
    reactionTime: "1ms",
    warrantyType: "Official Distributor",
    panelType: "AH IPS",
    Imagingtechnology: "LED",
    chechFavorites: false,
    favoriteId: 36,
  },
  {
    id: 5,
    name: "P2720d",
    image: "dell.jpg",
    imageFile: "MonitorImage",
    description: " 60hz 8ms (hdmi+display) Qhd Ips Monitor",
    brand: "Dell",
    category: "monitor",
    price: 799,
    countInStock: 106,
    rating: 5,
    numReviews: 315,
    screenSize: 27,
    resolution: "2160 x 1440",
    reactionTime: "8ms",
    warrantyType: "Official Distributor",
    panelType: "IPS",
    Imagingtechnology: "IPS",
    chechFavorites: false,
    favoriteId: 37,
  },
  {
    id: 6,
    name: "Va2432-h",
    image: "viewSonic.webp",
    imageFile: "MonitorImage",
    description: " 4ms, 75hz, Analog, Hdmi, Ips Led, Monitor",
    brand: "ViewSonic",
    category: "monitor",
    price: 339,
    countInStock: 148,
    rating: 3,
    numReviews: 267,
    screenSize: 23.8,
    resolution: "3840 x 2160",
    reactionTime: "4ms",
    warrantyType: "Official Distributor",
    panelType: "IPS",
    Imagingtechnology: "LED",
    chechFavorites: false,
    favoriteId: 38,
  },
  {
    id: 7,
    name: "TUF Gaming VG27VQ",
    image: "asus.webp",
    imageFile: "MonitorImage",
    description:
      " 165 Hz 1ms (HDMI+Display+DVI-D) FreeSync Full HD Curved Monitor",
    brand: "Asus",
    category: "monitor",
    price: 599,
    countInStock: 192,
    rating: 4,
    numReviews: 272,
    screenSize: 27,
    resolution: "1920 x 1080",
    reactionTime: "1ms",
    warrantyType: "Official Distributor",
    panelType: "VA",
    Imagingtechnology: "LED",
    chechFavorites: false,
    favoriteId: 39,
  },
  {
    id: 8,
    name: "Aryond A32",
    image: "monster.webp",
    imageFile: "MonitorImage",
    description: "165hz 1ms (hdmi+display) G-sync Qhd Led Monitor",
    brand: "Monster",
    category: "monitor",
    price: 899,
    countInStock: 158,
    rating: 3,
    numReviews: 279,
    screenSize: 32,
    resolution: "2560 x 1440",
    reactionTime: "1ms",
    warrantyType: "Official Distributor",
    panelType: "MVA",
    Imagingtechnology: "LED",
    chechFavorites: false,
    favoriteId: 40,
  },
];

export default MonitorData;
