const PhoneData = [
  {
    id: 1,
    name: "iPhone 11",
    image: "iphone.webp",
    imageFile: "PhoneImage",
    description: "128GB Box White Cell Phone Without Accessories",
    brand: "Apple",
    category: "phone",
    price: 1099,
    countInStock: 26,
    rating: 5,
    numReviews: 486,
    warrantyType: "Apple Guarantee",
    ram: "4 GB",
    batteryPower: "3000-4000",
    internalMemory: "128 GB",
    Links: "Wi-Fi",
    screenSize: "6 inches and up",
    chechFavorites: false,
    productUnicId: 9,
  },
  {
    id: 2,
    name: "Redmi 10",
    image: "xiaomi.webp",
    imageFile: "PhoneImage",
    description: "2022 4GB Ram + 64GB Gray Mobile Phone",
    brand: "Xiaomi",
    category: "phone",
    price: 599,
    countInStock: 46,
    rating: 4,
    numReviews: 326,
    warrantyType: "Official Distributor",
    ram: "4 GB",
    batteryPower: "3000-4000",
    internalMemory: "64 GB",
    Links: "Wi-Fi",
    screenSize: "6.5 inches and up",
    chechFavorites: false,
    productUnicId: 10,
  },
  {
    id: 3,
    name: " P13 Blue Max Lite",
    image: "reeder.webp",
    imageFile: "PhoneImage",
    description: "Reeder P13 Blue Max Lite 2022 32 GB",
    brand: "Reeder",
    category: "phone",
    price: 399,
    countInStock: 88,
    rating: 3,
    numReviews: 541,
    warrantyType: "Official Distributor",
    ram: "2 GB",
    batteryPower: "2000-3000",
    internalMemory: "64 GB",
    Links: "Wi-Fi",
    screenSize: "6 inches and up",
    chechFavorites: false,
    productUnicId: 11,
  },
  {
    id: 4,
    name: " C11 2021",
    image: "realme.webp",
    imageFile: "PhoneImage",
    description: "32GB Blue Mobile Phone",
    brand: "Realme",
    category: "phone",
    price: 599,
    countInStock: 105,
    rating: 2,
    numReviews: 473,
    warrantyType: "Official Distributor",
    ram: "2 GB",
    batteryPower: "4000-5000",
    internalMemory: "32 GB",
    Links: "Wi-Fi",
    screenSize: "6 inches and up",
    chechFavorites: false,
    productUnicId: 12,
  },
  {
    id: 5,
    name: " Galaxy A32",
    image: "samsung.webp",
    imageFile: "PhoneImage",
    description: "128GB Purple Mobile Phone",
    brand: "Samsung",
    category: "phone",
    price: 999,
    countInStock: 124,
    rating: 4,
    numReviews: 468,
    warrantyType: "Samsung Guarantee",
    ram: "6 GB",
    batteryPower: "4000-5000",
    internalMemory: "128 GB",
    Links: "Wi-Fi",
    screenSize: "6 inches and up",
    chechFavorites: false,
    productUnicId: 13,
  },
  {
    id: 6,
    name: " A16",
    image: "oppo.webp",
    imageFile: "PhoneImage",
    description: "3GB+32GB Black Mobile Phone",
    brand: "Oppo",
    category: "phone",
    price: 599,
    countInStock: 144,
    rating: 5,
    numReviews: 368,
    warrantyType: "Oppo Guarantee",
    ram: "4 GB",
    batteryPower: "5000-6000",
    internalMemory: "32 GB",
    Links: "Wi-Fi",
    screenSize: "6.5 inches and up",
    chechFavorites: false,
    productUnicId: 14,
  },
  {
    id: 7,
    name: "  X4",
    image: "poco.webp",
    imageFile: "PhoneImage",
    description: "8gb+256gb Black Mobile Phone X4 Pro",
    brand: "Poco",
    category: "phone",
    price: 899,
    countInStock: 153,
    rating: 4,
    numReviews: 248,
    warrantyType: "Xiaomi Guarantee",
    ram: "8 GB",
    batteryPower: "3000-7900",
    internalMemory: "256 GB",
    Links: "Wi-Fi",
    screenSize: "6 inches and up",
    chechFavorites: false,
    productUnicId: 15,
  },
  {
    id: 8,
    name: "  Pova 3",
    image: "tecno.webp",
    imageFile: "PhoneImage",
    description: "128 Gb 6+5 Gb Ram-128gb Blue",
    brand: "Tecno",
    category: "phone",
    price: 499,
    countInStock: 182,
    rating: 3,
    numReviews: 378,
    warrantyType: "Official Distributor",
    ram: "6 GB",
    batteryPower: "3000-7900",
    internalMemory: "128 GB",
    Links: "Wi-Fi",
    screenSize: "6.8 inches and up",
    chechFavorites: false,
    productUnicId: 16,
  },
];

export default PhoneData;
