const TelevisionData = [
  {
    id: 1,
    name: "OV32150",
    image: "onvo.webp",
    imageFile: "TelevisionImage",
    description: "81 Screen HD Ready Smart LED TV with Satellite Receiver",
    brand: "Onvo",
    category: "television",
    price: 499,
    countInStock: 33,
    rating: 4,
    numReviews: 48,
    screenSize: "81 Screen",
    smartTv: "There is",
    ımagingTechnology: "LED",
    warrantyType: "Official Distributor",
    builtInSatelliteReceiver: "There is",
    ımageQuality: "HD Ready",
    chechFavorites: false,
    productUnicId: 25,
  },
  {
    id: 2,
    name: "50R754U",
    image: "regal.webp",
    imageFile: "TelevisionImage",
    description: "126 Screen 4K Ultra HD Smart LED TV with Satellite Receiver",
    brand: "Regal",
    category: "television",
    price: 699,
    countInStock: 43,
    rating: 3,
    numReviews: 72,
    screenSize: "126 Screen",
    smartTv: "There is",
    ımagingTechnology: "LED",
    warrantyType: "Vestel Guarantee",
    builtInSatelliteReceiver: "There is",
    ımageQuality: "4K Ultra HD",
    chechFavorites: false,
    productUnicId: 26,
  },
  {
    id: 3,
    name: "50U9600",
    image: "vestel.webp",
    imageFile: "TelevisionImage",
    description:
      "127 Screen Satellite Receiver 4K Ultra HD Smart LED TV TV-U9600",
    brand: "Vestel",
    category: "television",
    price: 799,
    countInStock: 92,
    rating: 2,
    numReviews: 102,
    screenSize: "127 Screen",
    smartTv: "There is",
    ımagingTechnology: "LED",
    warrantyType: "Vestel Guarantee",
    builtInSatelliteReceiver: "There is",
    ımageQuality: "4K Ultra HD",
    chechFavorites: false,
    productUnicId: 27,
  },
  {
    id: 4,
    name: "SN55UAL402",
    image: "sunny.webp",
    imageFile: "TelevisionImage",
    description: "139 Screen 4K Ultra HD Smart LED TV with Satellite Receiver",
    brand: "Sunny",
    category: "television",
    price: 699,
    countInStock: 105,
    rating: 4,
    numReviews: 115,
    screenSize: "139 Screen",
    smartTv: "There is",
    ımagingTechnology: "LED",
    warrantyType: "Sunny Guarantee",
    builtInSatelliteReceiver: "There is",
    ımageQuality: "4K Ultra HD",
    chechFavorites: false,
    productUnicId: 28,
  },
  {
    id: 5,
    name: "50AU7000",
    image: "samsung.webp",
    imageFile: "TelevisionImage",
    description:
      "125 Screen Crystal 4K Ultra HD Smart LED TV with Satellite Receiver",
    brand: "Samsung",
    category: "television",
    price: 899,
    countInStock: 126,
    rating: 5,
    numReviews: 137,
    screenSize: "125 Screen",
    smartTv: "There is",
    ımagingTechnology: "LED",
    warrantyType: "Samsung Guarantee",
    builtInSatelliteReceiver: "There is",
    ımageQuality: "4K Ultra HD",
    chechFavorites: false,
    productUnicId: 29,
  },
  {
    id: 6,
    name: "50UA2063DT",
    image: "toshiba.webp",
    imageFile: "TelevisionImage",
    description:
      "127 Screen 4K Ultra HD Smart Android LED TV with Satellite Receiver",
    brand: "Toshiba",
    category: "television",
    price: 599,
    countInStock: 146,
    rating: 2,
    numReviews: 158,
    screenSize: "127 Screen",
    smartTv: "There is",
    ımagingTechnology: "LED",
    warrantyType: "Vestel Guarantee",
    builtInSatelliteReceiver: "There is",
    ımageQuality: "4K Ultra HD",
    chechFavorites: false,
    productUnicId: 30,
  },
  {
    id: 7,
    name: "GEU 7830",
    image: "grundig.jpg",
    imageFile: "TelevisionImage",
    description: "109 Screen 4K Ultra HD Smart LED TV with Satellite Receiver",
    brand: "Grundig",
    category: "television",
    price: 499,
    countInStock: 153,
    rating: 3,
    numReviews: 188,
    screenSize: "109 Screen",
    smartTv: "There is",
    ımagingTechnology: "LED",
    warrantyType: "Grundig Guarantee",
    builtInSatelliteReceiver: "There is",
    ımageQuality: "4K Ultra HD",
    chechFavorites: false,
    productUnicId: 31,
  },
  {
    id: 8,
    name: "50R754UA9",
    image: "regal.png",
    imageFile: "TelevisionImage",
    description:
      "126 Screen 4K Ultra HD Android Smart LED TV with Satellite Receiver",
    brand: "Regal",
    category: "television",
    price: 699,
    countInStock: 184,
    rating: 4,
    numReviews: 167,
    screenSize: "126 Screen",
    smartTv: "There is",
    ımagingTechnology: "LED",
    warrantyType: "Vestel Guarantee",
    builtInSatelliteReceiver: "There is",
    ımageQuality: "4K Ultra HD",
    chechFavorites: false,
    productUnicId: 32,
  },
];

export default TelevisionData;
