const LaptopData = [
  {
    id: "1",
    name: "MacBook Air",
    image: "macbook.webp",
    description: " 8-Core CPU 7-Core GPU 8GB Unified Memory 256GB SSD",
    brand: "Apple",
    category: "Electronics",
    price: 999,
    countInStock: 10,
    rating: 4,
    numReviews: 12,
  },
  {
    id: "2",
    name: "Casper Excalibur",
    image: "casper.webp",
    description:
      "Excalibur G911.1270-bv60x-b Intel I7-12700h 16gb Ram 500gb Ssd 6gb Rtx3060",
    brand: "Casper",
    category: "Electronics",
    price: 1199,
    countInStock: 15,
    rating: 3,
    numReviews: 17,
  },
  {
    id: "3",
    name: "Hp Victus",
    image: "hp.webp",
    description: "Ryzen 7 6800h 16gb Ram 512gb Ssd 4gb Rtx3050ti",
    brand: "Hp",
    category: "Electronics",
    price: 899,
    countInStock: 23,
    rating: 4,
    numReviews: 19,
  },
  {
    id: "4",
    name: "Asus Rog Strıx",
    image: "asus.jpg",
    description: "I9-12950hx 32gb 4tb Ssd 16gb Rtx3080tı",
    brand: "Asus",
    category: "Electronics",
    price: 5999,
    countInStock: 3,
    rating: 5,
    numReviews: 112,
  },
  {
    id: "5",
    name: "Monster Abra",
    image: "monster.webp",
    description: "Intel Core I5-12500h 8 Gb Ram 500gb Ssd 4gb Gtx1650",
    brand: "Monster",
    category: "Electronics",
    price: 799,
    countInStock: 26,
    rating: 2,
    numReviews: 12,
  },
  {
    id: "6",
    name: "Msi Alpha",
    image: "msi.webp",
    description: "R7-5800H 16GB DDR4 RX6600M GDDR6 8GB 512GB SSD",
    brand: "Msi",
    category: "Electronics",
    price: 899,
    countInStock: 52,
    rating: 4,
    numReviews: 21,
  },
  {
    id: "7",
    name: "Hp Pavilion",
    image: "hp2.webp",
    description: "Intel Core I5 10300h Gtx1050",
    brand: "Hp",
    category: "Electronics",
    price: 699,
    countInStock: 38,
    rating: 1,
    numReviews: 29,
  },
  {
    id: "8",
    name: "Msi Thın",
    image: "msi2.webp",
    description: "I5-10500h 8gb Ram 256gb Ssd Gtx1650",
    brand: "Msi",
    category: "Electronics",
    price: 899.00,
    countInStock: 43,
    rating: 2,
    numReviews: 46,
  },
  {
    id: "9",
    name: "Asus Zenbook",
    image: "asus2.webp",
    description: "I7 12700h-32gb-1tb-15.6-rtx3060",
    brand: "Asus",
    category: "Electronics",
    price: 3999,
    countInStock: 43,
    rating: 2,
    numReviews: 46,
  },
];

export default LaptopData;
